import "./App.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import HeroSection from "./Components/HeroSection";
import { useState } from "react";

const CountryList = [
  {
    Id: 1,
    Name: "Afghanistan",
    ISOCode: "AF",
    ImageUrl: "https://flagcdn.com/w320/af.png",
    Alternative: "Afghanistan",
  },
  {
    Id: 2,
    Name: "Albania",
    ISOCode: "AL",
    ImageUrl: "https://flagcdn.com/w320/al.png",
    Alternative: "Albania",
  },
  {
    Id: 3,
    Name: "Algeria",
    ISOCode: "DZ",
    ImageUrl: "https://flagcdn.com/w320/dz.png",
    Alternative: "Algeria",
  },
  {
    Id: 4,
    Name: "Andorra",
    ISOCode: "AD",
    ImageUrl: "https://flagcdn.com/w320/ad.png",
    Alternative: "Andorra",
  },
  {
    Id: 5,
    Name: "Angola",
    ISOCode: "AO",
    ImageUrl: "https://flagcdn.com/w320/ao.png",
    Alternative: "Angola",
  },
  {
    Id: 6,
    Name: "Antigua and Barbuda",
    ISOCode: "AG",
    ImageUrl: "https://flagcdn.com/w320/ag.png",
    Alternative: "Antigua and Barbuda",
  },
  {
    Id: 7,
    Name: "Argentina",
    ISOCode: "AR",
    ImageUrl: "https://flagcdn.com/w320/ar.png",
    Alternative: "Argentina",
  },
  {
    Id: 8,
    Name: "Armenia",
    ISOCode: "AM",
    ImageUrl: "https://flagcdn.com/w320/am.png",
    Alternative: "Armenia",
  },
  {
    Id: 9,
    Name: "Australia",
    ISOCode: "AU",
    ImageUrl: "https://flagcdn.com/w320/au.png",
    Alternative: "Australia",
  },
  {
    Id: 10,
    Name: "Austria",
    ISOCode: "AT",
    ImageUrl: "https://flagcdn.com/w320/at.png",
    Alternative: "Austria",
  },
  {
    Id: 11,
    Name: "Azerbaijan",
    ISOCode: "AZ",
    ImageUrl: "https://flagcdn.com/w320/az.png",
    Alternative: "Azerbaijan",
  },
  {
    Id: 12,
    Name: "Bahamas",
    ISOCode: "BS",
    ImageUrl: "https://flagcdn.com/w320/bs.png",
    Alternative: "Bahamas",
  },
  {
    Id: 13,
    Name: "Bahrain",
    ISOCode: "BH",
    ImageUrl: "https://flagcdn.com/w320/bh.png",
    Alternative: "Bahrain",
  },
  {
    Id: 14,
    Name: "Bangladesh",
    ISOCode: "BD",
    ImageUrl: "https://flagcdn.com/w320/bd.png",
    Alternative: "Bangladesh",
  },
  {
    Id: 15,
    Name: "Barbados",
    ISOCode: "BB",
    ImageUrl: "https://flagcdn.com/w320/bb.png",
    Alternative: "Barbados",
  },
  {
    Id: 16,
    Name: "Belarus",
    ISOCode: "BY",
    ImageUrl: "https://flagcdn.com/w320/by.png",
    Alternative: "Belarus",
  },
  {
    Id: 17,
    Name: "Belgium",
    ISOCode: "BE",
    ImageUrl: "https://flagcdn.com/w320/be.png",
    Alternative: "Belgium",
  },
  {
    Id: 18,
    Name: "Belize",
    ISOCode: "BZ",
    ImageUrl: "https://flagcdn.com/w320/bz.png",
    Alternative: "Belize",
  },
  {
    Id: 19,
    Name: "Benin",
    ISOCode: "BJ",
    ImageUrl: "https://flagcdn.com/w320/bj.png",
    Alternative: "Benin",
  },
  {
    Id: 20,
    Name: "Bhutan",
    ISOCode: "BT",
    ImageUrl: "https://flagcdn.com/w320/bt.png",
    Alternative: "Bhutan",
  },
  {
    Id: 21,
    Name: "Bolivia",
    ISOCode: "BO",
    ImageUrl: "https://flagcdn.com/w320/bo.png",
    Alternative: "Bolivia",
  },
  {
    Id: 22,
    Name: "Bosnia and Herzegovina",
    ISOCode: "BA",
    ImageUrl: "https://flagcdn.com/w320/ba.png",
    Alternative: "Bosnia and Herzegovina",
  },
  {
    Id: 23,
    Name: "Botswana",
    ISOCode: "BW",
    ImageUrl: "https://flagcdn.com/w320/bw.png",
    Alternative: "Botswana",
  },
  {
    Id: 24,
    Name: "Brazil",
    ISOCode: "BR",
    ImageUrl: "https://flagcdn.com/w320/br.png",
    Alternative: "Brazil",
  },
  {
    Id: 25,
    Name: "Brunei",
    ISOCode: "BN",
    ImageUrl: "https://flagcdn.com/w320/bn.png",
    Alternative: "Brunei",
  },
  {
    Id: 26,
    Name: "Bulgaria",
    ISOCode: "BG",
    ImageUrl: "https://flagcdn.com/w320/bg.png",
    Alternative: "Bulgaria",
  },
  {
    Id: 27,
    Name: "Burkina Faso",
    ISOCode: "BF",
    ImageUrl: "https://flagcdn.com/w320/bf.png",
    Alternative: "Burkina Faso",
  },
  {
    Id: 28,
    Name: "Burundi",
    ISOCode: "BI",
    ImageUrl: "https://flagcdn.com/w320/bi.png",
    Alternative: "Burundi",
  },
  {
    Id: 29,
    Name: "Cabo Verde",
    ISOCode: "CV",
    ImageUrl: "https://flagcdn.com/w320/cv.png",
    Alternative: "Cabo Verde",
  },
  {
    Id: 30,
    Name: "Cambodia",
    ISOCode: "KH",
    ImageUrl: "https://flagcdn.com/w320/kh.png",
    Alternative: "Cambodia",
  },
  {
    Id: 31,
    Name: "Cameroon",
    ISOCode: "CM",
    ImageUrl: "https://flagcdn.com/w320/cm.png",
    Alternative: "Cameroon",
  },
  {
    Id: 32,
    Name: "Canada",
    ISOCode: "CA",
    ImageUrl: "https://flagcdn.com/w320/ca.png",
    Alternative: "Canada",
  },
  {
    Id: 33,
    Name: "Central African Republic",
    ISOCode: "CF",
    ImageUrl: "https://flagcdn.com/w320/cf.png",
    Alternative: "Central African Republic",
  },
  {
    Id: 34,
    Name: "Chad",
    ISOCode: "TD",
    ImageUrl: "https://flagcdn.com/w320/td.png",
    Alternative: "Chad",
  },
  {
    Id: 35,
    Name: "Chile",
    ISOCode: "CL",
    ImageUrl: "https://flagcdn.com/w320/cl.png",
    Alternative: "Chile",
  },
  {
    Id: 36,
    Name: "China",
    ISOCode: "CN",
    ImageUrl: "https://flagcdn.com/w320/cn.png",
    Alternative: "China",
  },
  {
    Id: 37,
    Name: "Colombia",
    ISOCode: "CO",
    ImageUrl: "https://flagcdn.com/w320/co.png",
    Alternative: "Colombia",
  },
  {
    Id: 38,
    Name: "Comoros",
    ISOCode: "KM",
    ImageUrl: "https://flagcdn.com/w320/km.png",
    Alternative: "Comoros",
  },
  {
    Id: 39,
    Name: "Congo ",
    ISOCode: "CG",
    ImageUrl: "https://flagcdn.com/w320/cg.png",
    Alternative: "Congo ",
  },
  {
    Id: 40,
    Name: "Republic of Congo",
    ISOCode: "CD",
    ImageUrl: "https://flagcdn.com/w320/cd.png",
    Alternative: "Republic of Congo",
  },
  {
    Id: 41,
    Name: "Costa Rica",
    ISOCode: "CR",
    ImageUrl: "https://flagcdn.com/w320/cr.png",
    Alternative: "Costa Rica",
  },
  {
    Id: 42,
    Name: "Croatia",
    ISOCode: "HR",
    ImageUrl: "https://flagcdn.com/w320/hr.png",
    Alternative: "Croatia",
  },
  {
    Id: 43,
    Name: "Cuba",
    ISOCode: "CU",
    ImageUrl: "https://flagcdn.com/w320/cu.png",
    Alternative: "Cuba",
  },
  {
    Id: 44,
    Name: "Cyprus",
    ISOCode: "CY",
    ImageUrl: "https://flagcdn.com/w320/cy.png",
    Alternative: "Cyprus",
  },
  {
    Id: 45,
    Name: "Czechia",
    ISOCode: "CZ",
    ImageUrl: "https://flagcdn.com/w320/cz.png",
    Alternative: "Czechia",
  },
  {
    Id: 46,
    Name: "Denmark",
    ISOCode: "DK",
    ImageUrl: "https://flagcdn.com/w320/dk.png",
    Alternative: "Denmark",
  },
  {
    Id: 47,
    Name: "Djibouti",
    ISOCode: "DJ",
    ImageUrl: "https://flagcdn.com/w320/dj.png",
    Alternative: "Djibouti",
  },
  {
    Id: 48,
    Name: "Dominica",
    ISOCode: "DM",
    ImageUrl: "https://flagcdn.com/w320/dm.png",
    Alternative: "Dominica",
  },
  {
    Id: 49,
    Name: "Dominican Republic",
    ISOCode: "DO",
    ImageUrl: "https://flagcdn.com/w320/do.png",
    Alternative: "Dominican Republic",
  },
  {
    Id: 50,
    Name: "Ecuador",
    ISOCode: "EC",
    ImageUrl: "https://flagcdn.com/w320/ec.png",
    Alternative: "Ecuador",
  },
  {
    Id: 51,
    Name: "Egypt",
    ISOCode: "EG",
    ImageUrl: "https://flagcdn.com/w320/eg.png",
    Alternative: "Egypt",
  },
  {
    Id: 52,
    Name: "El Salvador",
    ISOCode: "SV",
    ImageUrl: "https://flagcdn.com/w320/sv.png",
    Alternative: "El Salvador",
  },
  {
    Id: 53,
    Name: "Equatorial Guinea",
    ISOCode: "GQ",
    ImageUrl: "https://flagcdn.com/w320/gq.png",
    Alternative: "Equatorial Guinea",
  },
  {
    Id: 54,
    Name: "Eritrea",
    ISOCode: "ER",
    ImageUrl: "https://flagcdn.com/w320/er.png",
    Alternative: "Eritrea",
  },
  {
    Id: 55,
    Name: "Estonia",
    ISOCode: "EE",
    ImageUrl: "https://flagcdn.com/w320/ee.png",
    Alternative: "Estonia",
  },
  {
    Id: 56,
    Name: "Eswatini",
    ISOCode: "SZ",
    ImageUrl: "https://flagcdn.com/w320/sz.png",
    Alternative: "Eswatini",
  },
  {
    Id: 57,
    Name: "Ethiopia",
    ISOCode: "ET",
    ImageUrl: "https://flagcdn.com/w320/et.png",
    Alternative: "Ethiopia",
  },
  {
    Id: 58,
    Name: "Fiji",
    ISOCode: "FJ",
    ImageUrl: "https://flagcdn.com/w320/fj.png",
    Alternative: "Fiji",
  },
  {
    Id: 59,
    Name: "Finland",
    ISOCode: "FI",
    ImageUrl: "https://flagcdn.com/w320/fi.png",
    Alternative: "Finland",
  },
  {
    Id: 60,
    Name: "France",
    ISOCode: "FR",
    ImageUrl: "https://flagcdn.com/w320/fr.png",
    Alternative: "France",
  },
  {
    Id: 61,
    Name: "Gabon",
    ISOCode: "GA",
    ImageUrl: "https://flagcdn.com/w320/ga.png",
    Alternative: "Gabon",
  },
  {
    Id: 62,
    Name: "Gambia",
    ISOCode: "GM",
    ImageUrl: "https://flagcdn.com/w320/gm.png",
    Alternative: "Gambia",
  },
  {
    Id: 63,
    Name: "Georgia",
    ISOCode: "GE",
    ImageUrl: "https://flagcdn.com/w320/ge.png",
    Alternative: "Georgia",
  },
  {
    Id: 64,
    Name: "Germany",
    ISOCode: "DE",
    ImageUrl: "https://flagcdn.com/w320/de.png",
    Alternative: "Germany",
  },
  {
    Id: 65,
    Name: "Ghana",
    ISOCode: "GH",
    ImageUrl: "https://flagcdn.com/w320/gh.png",
    Alternative: "Ghana",
  },
  {
    Id: 66,
    Name: "Greece",
    ISOCode: "GR",
    ImageUrl: "https://flagcdn.com/w320/gr.png",
    Alternative: "Greece",
  },
  {
    Id: 67,
    Name: "Grenada",
    ISOCode: "GD",
    ImageUrl: "https://flagcdn.com/w320/gd.png",
    Alternative: "Grenada",
  },
  {
    Id: 68,
    Name: "Guatemala",
    ISOCode: "GT",
    ImageUrl: "https://flagcdn.com/w320/gt.png",
    Alternative: "Guatemala",
  },
  {
    Id: 69,
    Name: "Guinea",
    ISOCode: "GN",
    ImageUrl: "https://flagcdn.com/w320/gn.png",
    Alternative: "Guinea",
  },
  {
    Id: 70,
    Name: "Guinea-Bissau",
    ISOCode: "GW",
    ImageUrl: "https://flagcdn.com/w320/gw.png",
    Alternative: "Guinea-Bissau",
  },
  {
    Id: 71,
    Name: "Guyana",
    ISOCode: "GY",
    ImageUrl: "https://flagcdn.com/w320/gy.png",
    Alternative: "Guyana",
  },
  {
    Id: 72,
    Name: "Haiti",
    ISOCode: "HT",
    ImageUrl: "https://flagcdn.com/w320/ht.png",
    Alternative: "Haiti",
  },
  {
    Id: 73,
    Name: "Honduras",
    ISOCode: "HN",
    ImageUrl: "https://flagcdn.com/w320/hn.png",
    Alternative: "Honduras",
  },
  {
    Id: 74,
    Name: "Hungary",
    ISOCode: "HU",
    ImageUrl: "https://flagcdn.com/w320/hu.png",
    Alternative: "Hungary",
  },
  {
    Id: 75,
    Name: "Iceland",
    ISOCode: "IS",
    ImageUrl: "https://flagcdn.com/w320/is.png",
    Alternative: "Iceland",
  },
  {
    Id: 76,
    Name: "India",
    ISOCode: "IN",
    ImageUrl: "https://flagcdn.com/w320/in.png",
    Alternative: "India",
  },
  {
    Id: 77,
    Name: "Indonesia",
    ISOCode: "Id",
    ImageUrl: "https://flagcdn.com/w320/id.png",
    Alternative: "Indonesia",
  },
  {
    Id: 78,
    Name: "Iran",
    ISOCode: "IR",
    ImageUrl: "https://flagcdn.com/w320/ir.png",
    Alternative: "Iran",
  },
  {
    Id: 79,
    Name: "Iraq",
    ISOCode: "IQ",
    ImageUrl: "https://flagcdn.com/w320/iq.png",
    Alternative: "Iraq",
  },
  {
    Id: 80,
    Name: "Ireland",
    ISOCode: "IE",
    ImageUrl: "https://flagcdn.com/w320/ie.png",
    Alternative: "Ireland",
  },
  {
    Id: 81,
    Name: "Israel",
    ISOCode: "IL",
    ImageUrl: "https://flagcdn.com/w320/il.png",
    Alternative: "Israel",
  },
  {
    Id: 82,
    Name: "Italy",
    ISOCode: "IT",
    ImageUrl: "https://flagcdn.com/w320/it.png",
    Alternative: "Italy",
  },
  {
    Id: 83,
    Name: "Jamaica",
    ISOCode: "JM",
    ImageUrl: "https://flagcdn.com/w320/jm.png",
    Alternative: "Jamaica",
  },
  {
    Id: 84,
    Name: "Japan",
    ISOCode: "JP",
    ImageUrl: "https://flagcdn.com/w320/jp.png",
    Alternative: "Japan",
  },
  {
    Id: 85,
    Name: "Jordan",
    ISOCode: "JO",
    ImageUrl: "https://flagcdn.com/w320/jo.png",
    Alternative: "Jordan",
  },
  {
    Id: 86,
    Name: "Kazakhstan",
    ISOCode: "KZ",
    ImageUrl: "https://flagcdn.com/w320/kz.png",
    Alternative: "Kazakhstan",
  },
  {
    Id: 87,
    Name: "Kenya",
    ISOCode: "KE",
    ImageUrl: "https://flagcdn.com/w320/ke.png",
    Alternative: "Kenya",
  },
  {
    Id: 88,
    Name: "Kiribati",
    ISOCode: "KI",
    ImageUrl: "https://flagcdn.com/w320/ki.png",
    Alternative: "Kiribati",
  },
  {
    Id: 89,
    Name: "Korea (North)",
    ISOCode: "KP",
    ImageUrl: "https://flagcdn.com/w320/kp.png",
    Alternative: "Korea (North)",
  },
  {
    Id: 90,
    Name: "Korea (South)",
    ISOCode: "KR",
    ImageUrl: "https://flagcdn.com/w320/kr.png",
    Alternative: "Korea (South)",
  },
  {
    Id: 91,
    Name: "Kuwait",
    ISOCode: "KW",
    ImageUrl: "https://flagcdn.com/w320/kw.png",
    Alternative: "Kuwait",
  },
  {
    Id: 92,
    Name: "Kyrgyzstan",
    ISOCode: "KG",
    ImageUrl: "https://flagcdn.com/w320/kg.png",
    Alternative: "Kyrgyzstan",
  },
  {
    Id: 93,
    Name: "Laos",
    ISOCode: "LA",
    ImageUrl: "https://flagcdn.com/w320/la.png",
    Alternative: "Laos",
  },
  {
    Id: 94,
    Name: "Latvia",
    ISOCode: "LV",
    ImageUrl: "https://flagcdn.com/w320/lv.png",
    Alternative: "Latvia",
  },
  {
    Id: 95,
    Name: "Lebanon",
    ISOCode: "LB",
    ImageUrl: "https://flagcdn.com/w320/lb.png",
    Alternative: "Lebanon",
  },
  {
    Id: 96,
    Name: "Lesotho",
    ISOCode: "LS",
    ImageUrl: "https://flagcdn.com/w320/ls.png",
    Alternative: "Lesotho",
  },
  {
    Id: 97,
    Name: "Liberia",
    ISOCode: "LR",
    ImageUrl: "https://flagcdn.com/w320/lr.png",
    Alternative: "Liberia",
  },
  {
    Id: 98,
    Name: "Libya",
    ISOCode: "LY",
    ImageUrl: "https://flagcdn.com/w320/ly.png",
    Alternative: "Libya",
  },
  {
    Id: 99,
    Name: "Liechtenstein",
    ISOCode: "LI",
    ImageUrl: "https://flagcdn.com/w320/li.png",
    Alternative: "Liechtenstein",
  },
  {
    Id: 100,
    Name: "Lithuania",
    ISOCode: "LT",
    ImageUrl: "https://flagcdn.com/w320/lt.png",
    Alternative: "Lithuania",
  },
  {
    Id: 101,
    Name: "Luxembourg",
    ISOCode: "LU",
    ImageUrl: "https://flagcdn.com/w320/lu.png",
    Alternative: "Luxembourg",
  },
  {
    Id: 102,
    Name: "Madagascar",
    ISOCode: "MG",
    ImageUrl: "https://flagcdn.com/w320/mg.png",
    Alternative: "Madagascar",
  },
  {
    Id: 103,
    Name: "Malawi",
    ISOCode: "MW",
    ImageUrl: "https://flagcdn.com/w320/mw.png",
    Alternative: "Malawi",
  },
  {
    Id: 104,
    Name: "Malaysia",
    ISOCode: "MY",
    ImageUrl: "https://flagcdn.com/w320/my.png",
    Alternative: "Malaysia",
  },
  {
    Id: 105,
    Name: "Maldives",
    ISOCode: "MV",
    ImageUrl: "https://flagcdn.com/w320/mv.png",
    Alternative: "Maldives",
  },
  {
    Id: 106,
    Name: "Mali",
    ISOCode: "ML",
    ImageUrl: "https://flagcdn.com/w320/ml.png",
    Alternative: "Mali",
  },
  {
    Id: 107,
    Name: "Malta",
    ISOCode: "MT",
    ImageUrl: "https://flagcdn.com/w320/mt.png",
    Alternative: "Malta",
  },
  {
    Id: 108,
    Name: "Marshall Islands",
    ISOCode: "MH",
    ImageUrl: "https://flagcdn.com/w320/mh.png",
    Alternative: "Marshall Islands",
  },
  {
    Id: 109,
    Name: "Mauritania",
    ISOCode: "MR",
    ImageUrl: "https://flagcdn.com/w320/mr.png",
    Alternative: "Mauritania",
  },
  {
    Id: 110,
    Name: "Mauritius",
    ISOCode: "MU",
    ImageUrl: "https://flagcdn.com/w320/mu.png",
    Alternative: "Mauritius",
  },
  {
    Id: 111,
    Name: "Mexico",
    ISOCode: "MX",
    ImageUrl: "https://flagcdn.com/w320/mx.png",
    Alternative: "Mexico",
  },
  {
    Id: 112,
    Name: "Micronesia",
    ISOCode: "FM",
    ImageUrl: "https://flagcdn.com/w320/fm.png",
    Alternative: "Micronesia",
  },
  {
    Id: 113,
    Name: "Moldova",
    ISOCode: "MD",
    ImageUrl: "https://flagcdn.com/w320/md.png",
    Alternative: "Moldova",
  },
  {
    Id: 114,
    Name: "Monaco",
    ISOCode: "MC",
    ImageUrl: "https://flagcdn.com/w320/mc.png",
    Alternative: "Monaco",
  },
  {
    Id: 115,
    Name: "Mongolia",
    ISOCode: "MN",
    ImageUrl: "https://flagcdn.com/w320/mn.png",
    Alternative: "Mongolia",
  },
  {
    Id: 116,
    Name: "Montenegro",
    ISOCode: "ME",
    ImageUrl: "https://flagcdn.com/w320/me.png",
    Alternative: "Montenegro",
  },
  {
    Id: 117,
    Name: "Morocco",
    ISOCode: "MA",
    ImageUrl: "https://flagcdn.com/w320/ma.png",
    Alternative: "Morocco",
  },
  {
    Id: 118,
    Name: "Mozambique",
    ISOCode: "MZ",
    ImageUrl: "https://flagcdn.com/w320/mz.png",
    Alternative: "Mozambique",
  },
  {
    Id: 119,
    Name: "Myanmar",
    ISOCode: "MM",
    ImageUrl: "https://flagcdn.com/w320/mm.png",
    Alternative: "Myanmar",
  },
  {
    Id: 120,
    Name: "Namibia",
    ISOCode: "NA",
    ImageUrl: "https://flagcdn.com/w320/na.png",
    Alternative: "Namibia",
  },
  {
    Id: 121,
    Name: "Nauru",
    ISOCode: "NR",
    ImageUrl: "https://flagcdn.com/w320/nr.png",
    Alternative: "Nauru",
  },
  {
    Id: 122,
    Name: "Nepal",
    ISOCode: "NP",
    ImageUrl: "https://flagcdn.com/w320/np.png",
    Alternative: "Nepal",
  },
  {
    Id: 123,
    Name: "Netherlands",
    ISOCode: "NL",
    ImageUrl: "https://flagcdn.com/w320/nl.png",
    Alternative: "Netherlands",
  },
  {
    Id: 124,
    Name: "New Zealand",
    ISOCode: "NZ",
    ImageUrl: "https://flagcdn.com/w320/nz.png",
    Alternative: "New Zealand",
  },
  {
    Id: 125,
    Name: "Nicaragua",
    ISOCode: "NI",
    ImageUrl: "https://flagcdn.com/w320/ni.png",
    Alternative: "Nicaragua",
  },
  {
    Id: 126,
    Name: "Niger",
    ISOCode: "NE",
    ImageUrl: "https://flagcdn.com/w320/ne.png",
    Alternative: "Niger",
  },
  {
    Id: 127,
    Name: "Nigeria",
    ISOCode: "NG",
    ImageUrl: "https://flagcdn.com/w320/ng.png",
    Alternative: "Nigeria",
  },
  {
    Id: 128,
    Name: "North Macedonia",
    ISOCode: "MK",
    ImageUrl: "https://flagcdn.com/w320/mk.png",
    Alternative: "North Macedonia",
  },
  {
    Id: 129,
    Name: "Norway",
    ISOCode: "NO",
    ImageUrl: "https://flagcdn.com/w320/no.png",
    Alternative: "Norway",
  },
  {
    Id: 130,
    Name: "Oman",
    ISOCode: "OM",
    ImageUrl: "https://flagcdn.com/w320/om.png",
    Alternative: "Oman",
  },
  {
    Id: 131,
    Name: "Pakistan",
    ISOCode: "PK",
    ImageUrl: "https://flagcdn.com/w320/pk.png",
    Alternative: "Pakistan",
  },
  {
    Id: 132,
    Name: "Palau",
    ISOCode: "PW",
    ImageUrl: "https://flagcdn.com/w320/pw.png",
    Alternative: "Palau",
  },
  {
    Id: 133,
    Name: "Panama",
    ISOCode: "PA",
    ImageUrl: "https://flagcdn.com/w320/pa.png",
    Alternative: "Panama",
  },
  {
    Id: 134,
    Name: "Papua New Guinea",
    ISOCode: "PG",
    ImageUrl: "https://flagcdn.com/w320/pg.png",
    Alternative: "Papua New Guinea",
  },
  {
    Id: 135,
    Name: "Paraguay",
    ISOCode: "PY",
    ImageUrl: "https://flagcdn.com/w320/py.png",
    Alternative: "Paraguay",
  },
  {
    Id: 136,
    Name: "Peru",
    ISOCode: "PE",
    ImageUrl: "https://flagcdn.com/w320/pe.png",
    Alternative: "Peru",
  },
  {
    Id: 137,
    Name: "Philippines",
    ISOCode: "PH",
    ImageUrl: "https://flagcdn.com/w320/ph.png",
    Alternative: "Philippines",
  },
  {
    Id: 138,
    Name: "Poland",
    ISOCode: "PL",
    ImageUrl: "https://flagcdn.com/w320/pl.png",
    Alternative: "Poland",
  },
  {
    Id: 139,
    Name: "Portugal",
    ISOCode: "PT",
    ImageUrl: "https://flagcdn.com/w320/pt.png",
    Alternative: "Portugal",
  },
  {
    Id: 140,
    Name: "Qatar",
    ISOCode: "QA",
    ImageUrl: "https://flagcdn.com/w320/qa.png",
    Alternative: "Qatar",
  },
  {
    Id: 141,
    Name: "Romania",
    ISOCode: "RO",
    ImageUrl: "https://flagcdn.com/w320/ro.png",
    Alternative: "Romania",
  },
  {
    Id: 142,
    Name: "Russia",
    ISOCode: "RU",
    ImageUrl: "https://flagcdn.com/w320/ru.png",
    Alternative: "Russia",
  },
  {
    Id: 143,
    Name: "Rwanda",
    ISOCode: "RW",
    ImageUrl: "https://flagcdn.com/w320/rw.png",
    Alternative: "Rwanda",
  },
  {
    Id: 144,
    Name: "Saint Kitts and Nevis",
    ISOCode: "KN",
    ImageUrl: "https://flagcdn.com/w320/kn.png",
    Alternative: "Saint Kitts and Nevis",
  },
  {
    Id: 145,
    Name: "Saint Lucia",
    ISOCode: "LC",
    ImageUrl: "https://flagcdn.com/w320/lc.png",
    Alternative: "Saint Lucia",
  },
  {
    Id: 146,
    Name: "Saint Vincent and the Grenadines",
    ISOCode: "VC",
    ImageUrl: "https://flagcdn.com/w320/vc.png",
    Alternative: "Saint Vincent and the Grenadines",
  },
  {
    Id: 147,
    Name: "Samoa",
    ISOCode: "WS",
    ImageUrl: "https://flagcdn.com/w320/ws.png",
    Alternative: "Samoa",
  },
  {
    Id: 148,
    Name: "San Marino",
    ISOCode: "SM",
    ImageUrl: "https://flagcdn.com/w320/sm.png",
    Alternative: "San Marino",
  },
  {
    Id: 149,
    Name: "Sao Tome and Principe",
    ISOCode: "ST",
    ImageUrl: "https://flagcdn.com/w320/st.png",
    Alternative: "Sao Tome and Principe",
  },
  {
    Id: 150,
    Name: "Saudi Arabia",
    ISOCode: "SA",
    ImageUrl: "https://flagcdn.com/w320/sa.png",
    Alternative: "Saudi Arabia",
  },
  {
    Id: 151,
    Name: "Senegal",
    ISOCode: "SN",
    ImageUrl: "https://flagcdn.com/w320/sn.png",
    Alternative: "Senegal",
  },
  {
    Id: 152,
    Name: "Serbia",
    ISOCode: "RS",
    ImageUrl: "https://flagcdn.com/w320/rs.png",
    Alternative: "Serbia",
  },
  {
    Id: 153,
    Name: "Seychelles",
    ISOCode: "SC",
    ImageUrl: "https://flagcdn.com/w320/sc.png",
    Alternative: "Seychelles",
  },
  {
    Id: 154,
    Name: "Sierra Leone",
    ISOCode: "SL",
    ImageUrl: "https://flagcdn.com/w320/sl.png",
    Alternative: "Sierra Leone",
  },
  {
    Id: 155,
    Name: "Singapore",
    ISOCode: "SG",
    ImageUrl: "https://flagcdn.com/w320/sg.png",
    Alternative: "Singapore",
  },
  {
    Id: 156,
    Name: "Slovakia",
    ISOCode: "SK",
    ImageUrl: "https://flagcdn.com/w320/sk.png",
    Alternative: "Slovakia",
  },
  {
    Id: 157,
    Name: "Slovenia",
    ISOCode: "SI",
    ImageUrl: "https://flagcdn.com/w320/si.png",
    Alternative: "Slovenia",
  },
  {
    Id: 158,
    Name: "Solomon Islands",
    ISOCode: "SB",
    ImageUrl: "https://flagcdn.com/w320/sb.png",
    Alternative: "Solomon Islands",
  },
  {
    Id: 159,
    Name: "Somalia",
    ISOCode: "SO",
    ImageUrl: "https://flagcdn.com/w320/so.png",
    Alternative: "Somalia",
  },
  {
    Id: 160,
    Name: "South Africa",
    ISOCode: "ZA",
    ImageUrl: "https://flagcdn.com/w320/za.png",
    Alternative: "South Africa",
  },
  {
    Id: 161,
    Name: "South Sudan",
    ISOCode: "SS",
    ImageUrl: "https://flagcdn.com/w320/ss.png",
    Alternative: "South Sudan",
  },
  {
    Id: 162,
    Name: "Spain",
    ISOCode: "ES",
    ImageUrl: "https://flagcdn.com/w320/es.png",
    Alternative: "Spain",
  },
  {
    Id: 163,
    Name: "Sri Lanka",
    ISOCode: "LK",
    ImageUrl: "https://flagcdn.com/w320/lk.png",
    Alternative: "Sri Lanka",
  },
  {
    Id: 164,
    Name: "Sudan",
    ISOCode: "SD",
    ImageUrl: "https://flagcdn.com/w320/sd.png",
    Alternative: "Sudan",
  },
  {
    Id: 165,
    Name: "Suriname",
    ISOCode: "SR",
    ImageUrl: "https://flagcdn.com/w320/sr.png",
    Alternative: "Suriname",
  },
  {
    Id: 166,
    Name: "Sweden",
    ISOCode: "SE",
    ImageUrl: "https://flagcdn.com/w320/se.png",
    Alternative: "Sweden",
  },
  {
    Id: 167,
    Name: "Switzerland",
    ISOCode: "CH",
    ImageUrl: "https://flagcdn.com/w320/ch.png",
    Alternative: "Switzerland",
  },
  {
    Id: 168,
    Name: "Syria",
    ISOCode: "SY",
    ImageUrl: "https://flagcdn.com/w320/sy.png",
    Alternative: "Syria",
  },
  {
    Id: 169,
    Name: "Taiwan",
    ISOCode: "TW",
    ImageUrl: "https://flagcdn.com/w320/tw.png",
    Alternative: "Taiwan",
  },
  {
    Id: 170,
    Name: "Tajikistan",
    ISOCode: "TJ",
    ImageUrl: "https://flagcdn.com/w320/tj.png",
    Alternative: "Tajikistan",
  },
  {
    Id: 171,
    Name: "Tanzania",
    ISOCode: "TZ",
    ImageUrl: "https://flagcdn.com/w320/tz.png",
    Alternative: "Tanzania",
  },
  {
    Id: 172,
    Name: "Thailand",
    ISOCode: "TH",
    ImageUrl: "https://flagcdn.com/w320/th.png",
    Alternative: "Thailand",
  },
  {
    Id: 173,
    Name: "Timor-Leste",
    ISOCode: "TL",
    ImageUrl: "https://flagcdn.com/w320/tl.png",
    Alternative: "Timor-Leste",
  },
  {
    Id: 174,
    Name: "Togo",
    ISOCode: "TG",
    ImageUrl: "https://flagcdn.com/w320/tg.png",
    Alternative: "Togo",
  },
  {
    Id: 175,
    Name: "Tonga",
    ISOCode: "TO",
    ImageUrl: "https://flagcdn.com/w320/to.png",
    Alternative: "Tonga",
  },
  {
    Id: 176,
    Name: "Trinidad and Tobago",
    ISOCode: "TT",
    ImageUrl: "https://flagcdn.com/w320/tt.png",
    Alternative: "Trinidad and Tobago",
  },
  {
    Id: 177,
    Name: "Tunisia",
    ISOCode: "TN",
    ImageUrl: "https://flagcdn.com/w320/tn.png",
    Alternative: "Tunisia",
  },
  {
    Id: 178,
    Name: "Turkey",
    ISOCode: "TR",
    ImageUrl: "https://flagcdn.com/w320/tr.png",
    Alternative: "Turkey",
  },
  {
    Id: 179,
    Name: "Turkmenistan",
    ISOCode: "TM",
    ImageUrl: "https://flagcdn.com/w320/tm.png",
    Alternative: "Turkmenistan",
  },
  {
    Id: 180,
    Name: "Tuvalu",
    ISOCode: "TV",
    ImageUrl: "https://flagcdn.com/w320/tv.png",
    Alternative: "Tuvalu",
  },
  {
    Id: 181,
    Name: "Uganda",
    ISOCode: "UG",
    ImageUrl: "https://flagcdn.com/w320/ug.png",
    Alternative: "Uganda",
  },
  {
    Id: 182,
    Name: "Ukraine",
    ISOCode: "UA",
    ImageUrl: "https://flagcdn.com/w320/ua.png",
    Alternative: "Ukraine",
  },
  {
    Id: 183,
    Name: "United Arab Emirates",
    ISOCode: "AE",
    ImageUrl: "https://flagcdn.com/w320/ae.png",
    Alternative: "United Arab Emirates",
  },
  {
    Id: 184,
    Name: "United Kingdom",
    ISOCode: "GB",
    ImageUrl: "https://flagcdn.com/w320/gb.png",
    Alternative: "United Kingdom",
  },
  {
    Id: 185,
    Name: "United States",
    ISOCode: "US",
    ImageUrl: "https://flagcdn.com/w320/us.png",
    Alternative: "United States",
  },
  {
    Id: 186,
    Name: "Uruguay",
    ISOCode: "UY",
    ImageUrl: "https://flagcdn.com/w320/uy.png",
    Alternative: "Uruguay",
  },
  {
    Id: 187,
    Name: "Uzbekistan",
    ISOCode: "UZ",
    ImageUrl: "https://flagcdn.com/w320/uz.png",
    Alternative: "Uzbekistan",
  },
  {
    Id: 188,
    Name: "Vanuatu",
    ISOCode: "VU",
    ImageUrl: "https://flagcdn.com/w320/vu.png",
    Alternative: "Vanuatu",
  },
  {
    Id: 189,
    Name: "Vatican City",
    ISOCode: "VA",
    ImageUrl: "https://flagcdn.com/w320/va.png",
    Alternative: "Vatican City",
  },
  {
    Id: 190,
    Name: "Venezuela",
    ISOCode: "VE",
    ImageUrl: "https://flagcdn.com/w320/ve.png",
    Alternative: "Venezuela",
  },
  {
    Id: 191,
    Name: "Vietnam",
    ISOCode: "VN",
    ImageUrl: "https://flagcdn.com/w320/vn.png",
    Alternative: "Vietnam",
  },
  {
    Id: 192,
    Name: "Yemen",
    ISOCode: "YE",
    ImageUrl: "https://flagcdn.com/w320/ye.png",
    Alternative: "Yemen",
  },
  {
    Id: 193,
    Name: "Zambia",
    ISOCode: "ZM",
    ImageUrl: "https://flagcdn.com/w320/zm.png",
    Alternative: "Zambia",
  },
  {
    Id: 194,
    Name: "Zimbabwe",
    ISOCode: "ZW",
    ImageUrl: "https://flagcdn.com/w320/zw.png",
    Alternative: "Zimbabwe",
  },
];

const App = () => {
  const [isCountrySelected,setIsCountrySelected] = useState(false)
 
  return (
    <>
    {/* {isCountrySelected ? :} */}
     <HeroSection />
      
    </>
  );
};

export default App;
